###

GET http://localhost:8080/betoffice-jweb/bo/office/ranking/roundonly/917

###

GET http://localhost:8080/betoffice-jweb/bo/office/ranking/season/31

###

GET http://localhost:8080/betoffice-jweb/bo/office/ping
Authorization: Bearer TestAuthorization

### Login

POST http://localhost:8080/betoffice-jweb/bo/office/login
Content-Type: application/json

{
    "nickname": "Frosch",
    "password": "awi"
}

### Logout

POST http://localhost:8080/betoffice-jweb/bo/office/logout
Content-Type: application/json
Authorization: Bearer ED22DB73592774A5A9CD02ACBE3302AA

{
    "nickname": "Frosch",
    "token": "075ED4256547D0EC908E2A6806CAC36F"
}
