###

GET http://localhost:8080/betoffice-jweb/bo/office/ranking/roundonly/917

###

GET http://localhost:8080/betoffice-jweb/bo/office/ranking/season/31

###

GET http://localhost:8080/betoffice-jweb/bo/office/ping
Authorization: Bearer TestAuthorization

###
http://127.0.0.1:8080/betoffice-jweb/bo/office/ranking/season/25
###
http://localhost:8080/betoffice-jweb/bo/office/ranking/season/30
###
http://127.0.0.1:8080/betoffice-jweb/bo/office/season/roundtable/695/group/62
###
https://tippdiekistebier.de/betoffice-jweb/

###
### Community management
###

GET http://localhost:8080/betoffice-jweb/bo/community-admin/communities


GET http://localhost:8080/betoffice-jweb/bo/community-admin/communities?page=1&size=20
Content-Type: application/json
betofficeToken: test


### Login

POST http://localhost:8080/betoffice-jweb/bo/office/login
Content-Type: application/json

{
    "nickname": "Frosch",
    "password": "awi"
}

### Logout

POST http://localhost:8080/betoffice-jweb/bo/office/logout
Content-Type: application/json
Authorization: Bearer E6AE13D88A936DB419DEAFFED8A08A98

{
    "nickname": "Frosch",
    "token": "075ED4256547D0EC908E2A6806CAC36F"
}

### TIPPDIEKISTEBIER:DE

GET https://tippdiekistebier.de/betoffice-jweb/bo/office/ping

###

GET http://tippdiekistebier.de:8080/betoffice-jweb/bo/office/ping

###

GET http://tippdiekistebier.de:8080/betoffice-jweb/bo/office/ranking/roundonly/917

###

GET https://tippdiekistebier.de/betoffice-jweb/bo/office/ranking/roundonly/917

### OpenLigaDb
https://www.openligadb.de/api/getmatchdata/bl1/2021/1
###
https://www.openligadb.de/api/getmatchdata/bl1
###