### Send request to the local Bootstrap server of betoffice.

###
GET http://localhost:7878/bo/office/ranking/roundonly/917

###

POST http://localhost:7878/bo/authentication/login
Content-Type: application/json

{
    "nickname": "Frosch",
    "password": "awi"
}

###

GET http://localhost:7878/bo/office/profile/Frosch
Content-Type: application/json
betofficeToken: 61219F6D3E1F3EF94364AE0BCB498891
betofficeNickname: Frosch
Authorization: Bearer 61219F6D3E1F3EF94364AE0BCB498891
